### ISSUE TITLE
modules not working

### ISSUE THREAD

**Issue by bhenderson** [fiatjaf/jiq#15]
I just discovered this and I'm really enjoying it.

I have custom modules defined in $HOME/.jq which are not working. My guess is that in jq.go the ENV is being set to empty and $HOME is not defined (untested). Is there a reason ENV is getting reset?

**Comment by bhenderson** [comment]
I just confirmed that commenting out `cmd.Env = make([]string, 0)` fixed my issue.

**Comment by fiatjaf** [comment]
Awesome. There is no reason, I don't understand why that line is there. Would you care to submit a patch removing that line entirely?
