### ISSUE TITLE
[Feature] Show query error in status area instead of in result area

### ISSUE THREAD

**Issue by erhhung** [fiatjaf/jiq#20]
Since `jiq` promotes itself as having the **full querying power of `jq`** as opposed to having just a simple drill down of a JSON document with `jid`, I would like to use it as an interactive query editor.

However, 90% of the time I see nothing but a **syntax error message** as I'm typing out my query and not being able to see the "previous" output.

Imagine running this command: `kubectl get services --all-namespaces -o json | jiq`
And then slowly typing this query: `.items[] | select(.metadata.namespace=="default")`

Everything after the pipe character and before the final close-parenthesis understandably yields an error, yet that is typically the part of the query I'd most want to see the previous output while I'm getting it right.

Instead of replacing the query result with the error message whenever an invalid query yields an error, how about **leaving the result area with the last successful query result** while **rendering the error message at the bottom of the screen** in a status area (show as many lines as needed, up to a reasonable limit)?

**Comment by fiatjaf** [comment]
I did a thing to preserve the previous output, but I'm not familiar enough with this termbox engine to know how to assign a new screen are just for the error, so I did the most dumb thing and just prepended the output with the error. I think it is good enough, but if you know how to do it properly please let me know!

**Comment by erhhung** [comment]
Thanks. It already helps a lot, just being able to still see the previous output. Where the error is shown is less important.
