### ISSUE TITLE
web-jiq doesnt work

### ISSUE THREAD

**Issue by pflegende** [fiatjaf/jiq#30]
may be the web-jiq doesnt work?

tried with opera, ff, chrome always newest upd on W10.
used only the example json-strings 
---
`{"aa":"2AA2","bb":{"aaa":[123,"cccc",[1,2]],"c":321}}  `

-> put into field "json-input"
---

`.bb.aaa[2]`

-> put it into field "view"
---

https://jq.fiatjaf.com/jiq/index.html

_There is no change on the screen_

Also on the site 
https://jq.fiatjaf.com/finder/index.html

its the same behaviour

May be you has some suggestion for me or a workaround?

CU
Happy new year!
:)

**Comment by fiatjaf** [comment]
This is the relevant repo: https://github.com/fiatjaf/jiq-web

**Comment by fiatjaf** [comment]
Something happen on the last deploy because of changes in the way emscripten works. The fix is to build jq-web again with emscripten and redeploy these sites.

**Comment by pflegende** [comment]
thx
:)
