### ISSUE TITLE
gobuiilder.me service is deprecated

### ISSUE THREAD

**Issue by ipwnponies** [fiatjaf/jiq#8]
The README for this repo links to gobuilder service for download of `jiq` binary. URL is broken because the [gobuilder service is deprecated](https://webcache.googleusercontent.com/search?q=cache:4ZXzreiU2eIJ:https://gobuilder.me/+) as of 2018-01-01.

**Comment by fiatjaf** [comment]
Is there a similar service somewhere?

**Comment by ipwnponies** [comment]
I'm not familiar with go ecosystem and alternative service. I'd suggest updating the README.md in the meanwhile to remove that point of confusion for new users (especially since it's presented as the first installation method).
